runtime: nodejs20

env: standard

instance_class: F2

env_variables:
  NODE_ENV: production
  # Add your OpenRouter API key here for server-side use
  # OPENROUTER_API_KEY: your-api-key-here

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
